#!/usr/bin/env bash
# Display numbers 1 to 20. For the 4th, 9th, and 17th iterations also
# display country specific superstition warning.

i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in
	    4)
		echo bad luck from China
		;;
	    9)
		echo bad luck from Japan
		;;
	    17)
		echo bad luck from Italy
		;;
	esac
	((i++))
done
