#!/usr/bin/env bash
# Fix container to run nginx as user: nginx on port 8080
pkill apache2
chmod u+rw /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i -E 's/(listen.*)80 /\18080 /g' /etc/nginx/sites-enabled/default
sudo -u nginx nginx
